export const ADD_COMPLAINS = 'ADD_COMPLAINS';
export const LOAD_COMPLAINS_LOADING = 'LOAD_COMPLAINS_LOADING';
export const LOAD_COMPLAINS_ERROR = 'LOAD_COMPLAINS_ERROR';

export const POST_COMPLAIN_SUCCESS = 'POST_COMPLAIN_SUCCESS';
export const POST_COMPLAIN_FAILURE = 'POST_COMPLAIN_FAILURE';

export const COMPLAIN_STATUS_CHANGE_SUCCESS = 'COMPLAIN_STATUS_CHANGE_SUCCESS';
export const COMPLAIN_STATUS_CHANGE_FAILURE = 'COMPLAIN_STATUS_CHANGE_FAILURE';
export const LOAD_USERS_LOADING  = 'LOAD_USERS_LOADING ';
export const ADD_USERS = "ADD_USERS";

export const ADD_TOAST = "ADD_TOAST";
export const REMOVE_TOAST = "REMOVE_TOAST";
export const ADD_BUSY_USERS = "ADD_BUSY_USERS";